language: python
python:
    - "3.5"
    - "3.4"
    - "3.3"
    - "3.2"
    - "2.7"
    - "pypy"
    - "pypy3"
install: 
    - pip install tox-travis
script: make test
before_install:
    - pip install codecov
after_success:
    - codecov
notifications:
    slack: raspberrypifoundation:YoIHtVdg8Hd6gcA09QEmCYXN
